### ISSUE TITLE
make TARGET=mess makes a build error

### ISSUE THREAD

**Issue by meesokim** [mamedev/roadmap#3]
make TARGET=mess
make: **\* No rule to make target 'scripts/target/mess/mess.lua', needed by 'build/projects/windows/mess/gmake-mingw32-gcc/Makefile'.  Stop.

It's based on the recent git.
make TARGET=mame has no problem.

at Windows 7 (32bit) Home Premium K Service pack 1.

**Comment by galibert** [comment]
make SUBTARGET=mess

The only other possible target is ldplayer.  Possible subtargets are mame,
mess, arcade and tiny.

  OG.

**Comment by meesokim** [comment]
I got it.
It's a big change!
MESS become a part of MAME totally.
Working perfectly!

I expected "mamemess" is the executable filename instead of mess.
But the executable file is still "mess".
Thank you for your help.
